import 'package:uuid/uuid.dart';

import '../models/payment.dart';
import '../models/tenant.dart';
import '../utils/month_utils.dart';
import 'payment_repository.dart';
import 'settings_service.dart';
import 'tenant_repository.dart';

/// Creates the rent record for each month as it comes around, so rent
/// counts as owed whether or not the landlord remembered to log it.
///
/// Without this the dashboard could cheerfully report "All settled up"
/// in the middle of a month whose rent simply had not been entered yet.
class RentScheduler {
  final TenantRepository tenantRepository;
  final PaymentRepository paymentRepository;
  final SettingsService settingsService;

  RentScheduler({
    TenantRepository? tenantRepository,
    PaymentRepository? paymentRepository,
    SettingsService? settingsService,
  })  : tenantRepository = tenantRepository ?? TenantRepository(),
        paymentRepository = paymentRepository ?? PaymentRepository(),
        settingsService = settingsService ?? SettingsService();

  /// Fills in any missing rent records up to and including this month.
  /// Returns how many were created. Safe to call on every launch.
  Future<int> reconcile() async {
    final settings = await settingsService.load();
    if (!settings.autoCreateMonthlyRent) return 0;

    final tenants = await tenantRepository.getAll();
    if (tenants.isEmpty) return 0;

    final payments = await paymentRepository.getAll();
    final currentMonth = MonthUtils.currentMonth();

    final created = <Payment>[];
    final updatedTenants = <Tenant>[];
    final currentMonthLabel = MonthUtils.format(currentMonth);
    // This runs on every visit to the Home tab, and is a no-op the vast
    // majority of the time, so don't rewrite the store for nothing.
    var tenantsChanged = false;

    for (final tenant in tenants) {
      // A tenant with no rent set has nothing meaningful to bill.
      if (tenant.monthlyRent <= 0) {
        updatedTenants.add(tenant);
        continue;
      }

      final from = _firstMonthToGenerate(tenant, payments, currentMonth);
      if (from == null || from.isAfter(currentMonth)) {
        updatedTenants.add(tenant);
        continue;
      }

      final existingMonths = payments
          .where((p) => p.tenantId == tenant.id)
          .map((p) => p.month)
          .toSet();

      for (var month = from;
          !month.isAfter(currentMonth);
          month = MonthUtils.addMonths(month, 1)) {
        final label = MonthUtils.format(month);
        if (existingMonths.contains(label)) continue;

        created.add(Payment(
          id: const Uuid().v4(),
          tenantId: tenant.id,
          month: label,
          amountDue: tenant.monthlyRent,
          amountPaid: 0,
          paidDate: '',
          referenceNumber: '',
          notes: '',
        ));
      }

      updatedTenants.add(tenant.copyWith(
        // Record the start we settled on, so it is not re-derived later.
        startMonth: tenant.startMonth.isEmpty
            ? MonthUtils.format(from)
            : tenant.startMonth,
        autoGeneratedThrough: currentMonthLabel,
      ));
      tenantsChanged = true;
    }

    if (created.isNotEmpty) {
      await paymentRepository.addAll(created);
    }
    if (tenantsChanged) {
      await tenantRepository.replaceAll(updatedTenants);
    }

    return created.length;
  }

  /// Where generation should start for this tenant: the month after the
  /// watermark if we have generated before, otherwise the tenancy start
  /// (falling back to their earliest recorded payment, then to today).
  DateTime? _firstMonthToGenerate(
    Tenant tenant,
    List<Payment> payments,
    DateTime currentMonth,
  ) {
    final watermark = MonthUtils.tryParse(tenant.autoGeneratedThrough);
    if (watermark != null) return MonthUtils.addMonths(watermark, 1);

    final start = MonthUtils.tryParse(tenant.startMonth);
    if (start != null) return start;

    final earliest = _earliestPaymentMonth(payments, tenant.id);
    return earliest ?? currentMonth;
  }

  DateTime? _earliestPaymentMonth(List<Payment> payments, String tenantId) {
    DateTime? earliest;
    for (final payment in payments) {
      if (payment.tenantId != tenantId) continue;
      final month = MonthUtils.tryParse(payment.month);
      if (month == null) continue;
      if (earliest == null || month.isBefore(earliest)) earliest = month;
    }
    return earliest;
  }
}
