/// A tenant/client the landlord rents a property to. Each tenant has their
/// own independent payment history.
class Tenant {
  final String id;
  final String name;
  final String phone;
  final String propertyDescription;
  final double monthlyRent;

  /// Month the tenancy began, e.g. "August 2026". Rent records are
  /// auto-created from here forward; empty means "unknown", in which case
  /// the earliest recorded payment (or the current month) is used.
  final String startMonth;

  /// Watermark for auto-created rent records: the last month generated
  /// for this tenant. Generation never looks back past it, so a record
  /// the landlord deliberately deleted is not resurrected next launch.
  final String autoGeneratedThrough;

  const Tenant({
    required this.id,
    required this.name,
    this.phone = '',
    this.propertyDescription = '',
    this.monthlyRent = 0.0,
    this.startMonth = '',
    this.autoGeneratedThrough = '',
  });

  Tenant copyWith({
    String? name,
    String? phone,
    String? propertyDescription,
    double? monthlyRent,
    String? startMonth,
    String? autoGeneratedThrough,
  }) {
    return Tenant(
      id: id,
      name: name ?? this.name,
      phone: phone ?? this.phone,
      propertyDescription: propertyDescription ?? this.propertyDescription,
      monthlyRent: monthlyRent ?? this.monthlyRent,
      startMonth: startMonth ?? this.startMonth,
      autoGeneratedThrough: autoGeneratedThrough ?? this.autoGeneratedThrough,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'phone': phone,
      'propertyDescription': propertyDescription,
      'monthlyRent': monthlyRent,
      'startMonth': startMonth,
      'autoGeneratedThrough': autoGeneratedThrough,
    };
  }

  factory Tenant.fromJson(Map<String, dynamic> json) {
    return Tenant(
      id: json['id'].toString(),
      name: json['name'].toString(),
      phone: json['phone']?.toString() ?? '',
      propertyDescription: json['propertyDescription']?.toString() ?? '',
      monthlyRent: json['monthlyRent'] is num
          ? (json['monthlyRent'] as num).toDouble()
          : double.tryParse(json['monthlyRent'].toString()) ?? 0.0,
      startMonth: json['startMonth']?.toString() ?? '',
      autoGeneratedThrough: json['autoGeneratedThrough']?.toString() ?? '',
    );
  }
}
